### ISSUE TITLE
unable to resolve path "compression"

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-boot#175]
I'm trying to load middleware via the options object rather than using middleware.json

```js
var options = { .. }
boot(app, options, function(err) {
```
however, with this config

```json
options: {
middleware:
   { 'initial:before': { 'loopback#favicon': {} },
     initial: { compression: {}, cors: [Object] },
     session: {},
     auth: {},
     parse: { 'body-parser#json': [Object] },
     routes: {},
     files: {},
     final: { 'loopback#urlNotFound': {} },
     'final:after': { errorhandler: {} } },
   }
...
}
```
I get the error
```
Error: Cannot resolve path "loopback"
    at resolveAppPath (/workspace/myapp/node_modules/loopback-boot/lib/compiler.js:356:15)
```
if I remove the "initial:before" line, so that "initial: { compression " is the first line, the error is

```
Error: Cannot resolve path "compression"
```

what am I missing, or not configuring ?

thanks

**Comment by NathanBWaters** [comment]
npm install compression fixed it for me

**Comment by superkhau** [comment]
@bajtos Is compression required for lb-boot? Wanted to ask before digging deeper to make sure (it's probably a requirement of body-parser, but figured you might know the answer off the top of your head).

**Comment by bajtos** [comment]
@jmls When booting via options, you need to include `appRootDir` in your options. Have you done that? Please provide us with a full sample reproducing the problem per https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

> Is compression required for lb-boot?

loopback-boot does not require any middleware, it just processes the configuration provided by the application. In this particular case, the application configures `loopback#favicon` and `compression` middleware, but loopback-boot cannot find them in the module paths it searches. This most likely means the list of module paths was built incorrectly, possibly because of missing `appRootDir`.

**Comment by davidcheung** [comment]
@jmls assuming this issue is solved by comment above since it has been stale for months, closing this issue now, please reopen if the issue still persist.
