### ISSUE TITLE
Resolve module paths as relative to appRootDir instead of `loopback-boot/lib`

### ISSUE THREAD

**Issue by raymondfeng** [strongloop/loopback-boot#73]
In some cases, we need to run an embedded sandbox application during tests so that `require` will be based on the root of the embedded application instead of the host module.

For example,

```
loopback-boot
  |_ test/fixure/test-app
                       |_ package.json
                       |_node_modules
                          |_test-module
```
See:

https://github.com/strongloop/loopback-boot/pull/70
https://github.com/strongloop/loopback/issues/833

**Comment by bajtos** [comment]
Typically, both loopback-boot and the module used from boot are sitting in the same node_modules folder:

```
project/
  node_modules/
    loopback-boot/
    boot-dependency/
```

When `require.resolve` does not find "boot-dependency" in `loopback-boot/node_modules`, it traverses the parent directories and eventually finds the module in `project/node_modules/boot-dependency`.

In order to reproduce the situation described by this GH issue, one can create the following file/directory structure in a unit-tests:

```
looopback-boot/
  sandbox/
   {app-uid}/
    node_modules/
      bootdep/
        index.js
        package.json # possibly not needed
```

And then reference "bootdep" from model sources, components and/or middleware config, e.g.

```
// sandbox/{app-uid}/middleware.json
{
  "initial": {
    "bootdep": { /*empty config */ }
  }
}
```

**Comment by bajtos** [comment]
@PradnyaBaviskar I think this issue should be fixed by your linked pull requests now, is that correct?

**Comment by PradnyaBaviskar** [comment]
Yes @bajtos, this would now be fixed with my linked PL.
