### ISSUE TITLE
Dynamic config options

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-boot#80]
It turns out that per-environment dynamic overrides via `config.{env}.js` are not good enough, as many users prefer to keep all config in a single javascript file (see e.g. #71). The current solution is to use `config.local.js` for that, even thought that file was initially intended for machine-local configuration that should not be checked into VCS (git, svn).

I am proposing to:
- [ ] Add a new suffix similar to `local`, files with this suffix will be always loaded. Possible suffixes: `dynamic`, `all`. This new suffix should be supported at least by `datasources.json`, `config.json` and `middleware.json`.
- [ ] Update the documentation and explain the difference between the new suffix and `local`, describe when to use which one.
- [ ] Add new unit tests to loopback-workspace to ensure it can handle missing config.json file. Possibly also change the implementation so that it does not create an empty config.json file.
- [ ]  Make the file `config.json` (and only this file) optional.

**Comment by bajtos** [comment]
Related: https://github.com/strongloop/loopback-boot/issues/84

**Comment by MarcDiethelm** [comment]
The current situation is surprisingly counter-intuitive for me. I expected `*.local.*` configs to be 
- of the highest priority of all config files, in order to override even ENV-specific configs files, for local (developer-specific) development.
- gitignored (again, because developer-specific)

(As far as I know that's how Sails does things, and I independently arrived at the same prioritization order in my own framework.)

As it stands however there is no way to, say force a DB port only in my personal development environment, if a ENV-specific config exists.
As I said this is pretty surprising. The only workaround that I can currently see is to set `NODE_ENV = 'local'`, which has it's own problems.

**Comment by jbcpollak** [comment]
This issue is of intense debate in my team. We would like to use .local.* files for local-only configuration, however we need global / all .js configuration as well, which is not currently supported.

In addition, as @MarcDiethelm points, .local files should be the highest priority, and excluded from version control.

I would add that I would like to see .local files NOT stored in the server/ directory at all, Lumping config (especially version-control ignored config files) with source code seems like a recipe for confusion.
